/* Core/Src/main.c — MCU-A (USB Host, SPI slave side) */

#include "main.h"
#include "gpio.h"
#include "spi.h"
#include "usb_host.h"

/* If you’re using the bridge helper I gave you earlier */
#include "spi_bridge_a.h"

/* From usb_host.c (generated by CubeMX) */
extern ApplicationTypeDef Appli_state;

/* Prototypes required by linker */
void SystemClock_Config(void);
void Error_Handler(void);

static void heartbeat(void)
{
  /* Optional: toggle an LED every ~200ms if you have one configured in gpio.c.
     Otherwise you can remove this function. */
  static uint32_t t0 = 0;
  if (HAL_GetTick() - t0 >= 200) {
    t0 = HAL_GetTick();
    /* Example: onboard LED on PA5. Adjust or remove if unused. */
    HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5);
  }
}

int main(void)
{
  HAL_Init();
  SystemClock_Config();

  MX_GPIO_Init();
  MX_SPI1_Init();        /* SPI1 configured as SLAVE in CubeMX */
  MX_USB_HOST_Init();    /* USB Host (MSC class) */

  /* Optionally signal boot OK: one quick blink */
  HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5);
  HAL_Delay(100);
  HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5);

  while (1)
  {
    /* Keep Host stack running */
    MX_USB_HOST_Process();

    /* When a USB stick is ready, service the SPI bridge so MCU-B can read/write */
    if (Appli_state == APPLICATION_READY) {
      /* This function should move data between USB MSC (disk) and SPI.
         If your file is named differently, call your service function here. */
      SPIA_Service();
    }

    heartbeat();
  }
}

/* ===== System Clock: HSI 16MHz -> PLL -> SYSCLK 84MHz, APB1 42MHz, APB2 84MHz ===== */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /* Power control clock enable (not strictly required on F4 for this setup) */
  __HAL_RCC_PWR_CLK_ENABLE();
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE2);

  /* HSI ON, PLL ON: VCO = 16MHz/8*336 = 672MHz, SYSCLK = 672/8 = 84MHz, USB = 48MHz */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;

  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
  RCC_OscInitStruct.PLL.PLLM = 8;
  RCC_OscInitStruct.PLL.PLLN = 336;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV4;  /* 84 MHz SYSCLK */
  RCC_OscInitStruct.PLL.PLLQ = 7;              /* 48 MHz for USB */

  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
    Error_Handler();
  }

  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK  |
                                RCC_CLOCKTYPE_SYSCLK|
                                RCC_CLOCKTYPE_PCLK1 |
                                RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider  = RCC_SYSCLK_DIV1;   /* 84 MHz */
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;     /* 42 MHz */
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;     /* 84 MHz */

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK) {
    Error_Handler();
  }

  /* Update the Systick to 1ms tick (HAL_Init set this, but keep consistent) */
  HAL_SYSTICK_Config(HAL_RCC_GetHCLKFreq()/1000);
  HAL_SYSTICK_CLKSourceConfig(SYSTICK_CLKSOURCE_HCLK);
}

/* ===== Minimal error handler used by CubeMX code in spi.c, usb_host.c, usbh_conf.c ===== */
void Error_Handler(void)
{
  __disable_irq();
  /* Solid LED + slow blink loop to indicate error; adjust pin if needed */
  HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_SET);
  while (1) {
    HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5);
    HAL_Delay(300);
  }
}

/* If you have USE_FULL_ASSERT enabled in stm32f4xx_hal_conf.h, add this too:
void assert_failed(uint8_t *file, uint32_t line)
{
  (void)file; (void)line;
  Error_Handler();
}
*/
