/* MCU-B: USB Device MSC (RAM disk for bring-up)
 * Board: STM32F411xE
 * CubeIDE: generated project with USB_DEVICE (MSC) + SPI1 enabled
 */

#include "main.h"
#include "usb_device.h"
#include "spi.h"    // generated by CubeMX, provides MX_SPI1_Init()
#include <string.h>

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
static void MX_GPIO_Init(void);

/* Main ----------------------------------------------------------------------*/
int main(void)
{
  HAL_Init();
  SystemClock_Config();
  MX_GPIO_Init();        // OK if empty; keeps Cube conventions
  MX_SPI1_Init();        // not strictly needed for RAM-disk test, but fine
  MX_USB_DEVICE_Init();  // <-- IMPORTANT: starts USB Device (MSC)

  // Optional: small delay to ensure host port is ready before connect
  HAL_Delay(50);

  while (1)
  {
    // Nothing needed here. The USB Device stack + ISR handle MSC.
    // You can set a temporary breakpoint here to see that firmware runs.
    HAL_Delay(100);
  }
}

/* Minimal GPIO init (safe no-LED default) -----------------------------------*/
static void MX_GPIO_Init(void)
{
  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOB_CLK_ENABLE();
  __HAL_RCC_GPIOC_CLK_ENABLE();
  // No pin config required for this bring-up.
}

/* Clock: HSI -> PLL (84MHz) with PLLQ=7 for USB 48MHz -----------------------*/
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  __HAL_RCC_PWR_CLK_ENABLE();
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE2);

  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;

  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
  /* For F4 USB: need 48MHz on PLLQ
     HSI=16MHz; PLLM=16 => VCOin=1MHz
     PLLN=336 => VCOout=336MHz
     PLLP=4   => SYSCLK=84MHz
     PLLQ=7   => 336/7 = 48MHz (USB) */
  RCC_OscInitStruct.PLL.PLLM = 16;
  RCC_OscInitStruct.PLL.PLLN = 336;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV4;
  RCC_OscInitStruct.PLL.PLLQ = 7;

  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
    Error_Handler();

  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK
                              | RCC_CLOCKTYPE_SYSCLK
                              | RCC_CLOCKTYPE_PCLK1
                              | RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider  = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
    Error_Handler();
}

/* Error handler -------------------------------------------------------------*/
void Error_Handler(void)
{
  __disable_irq();
  while (1) {
    // Trap here
  }
}
