#include "spi_bridge_a.h"
#include "spi.h"          // hspi1 (SLAVE)
#include "usb_host.h"     // hUsbHostFS, MX_USB_HOST_Process()
#include "usbh_msc.h"     // USBH_MSC_* API

/* ---- Protocol (matches MCU-B) -------------------------------------------
   'Q' -> reply:  'Q','O', ready(1), block_count(4 BE), block_size(2 BE)
   'R' hdr:       'R', lba(4 BE), cnt(2 BE)    -> reply 'O',0, then data
   'W' hdr:       'W', lba(4 BE), cnt(2 BE)    -> receive data, reply 'O',0
   Notes: cnt is small (<=8). Block size usually 512.
--------------------------------------------------------------------------- */

#define MAX_BLOCKS_PER_REQ   8
#define MAX_BLOCK_SIZE       512
#define BUF_SIZE             (MAX_BLOCKS_PER_REQ * MAX_BLOCK_SIZE)

static uint8_t xbuf[BUF_SIZE];   /* shared read/write buffer */

/* Externs generated by CubeMX */
extern USBH_HandleTypeDef hUsbHostFS;

/* From usb_host.c (CubeMX generates this symbol) */
extern ApplicationTypeDef Appli_state;

/* Helpers */
static inline uint8_t be_u32(uint32_t v, int i){ return (uint8_t)(v >> (8*(3-i))); }
static inline uint8_t be_u16(uint16_t v, int i){ return (i==0)? (uint8_t)(v>>8) : (uint8_t)v; }

static uint8_t rx_bytes(uint8_t *p, uint16_t n, uint32_t to_ms)
{
  return (HAL_SPI_Receive(&hspi1, p, n, to_ms) == HAL_OK) ? 0 : 1;
}
static uint8_t tx_bytes(const uint8_t *p, uint16_t n, uint32_t to_ms)
{
  return (HAL_SPI_Transmit(&hspi1, (uint8_t*)p, n, to_ms) == HAL_OK) ? 0 : 1;
}

/* Query media state/capacity from USB Host MSC */
static uint8_t get_media_info(uint8_t *ready, uint32_t *blk_cnt, uint16_t *blk_sz)
{
  *ready = 0;
  *blk_cnt = 0;
  *blk_sz  = 512;

  if (Appli_state != APPLICATION_READY) return 0;  // not mounted yet

  MSC_LUNTypeDef lun_info;
  if (USBH_MSC_GetLUNInfo(&hUsbHostFS, 0, &lun_info) == USBH_OK) {
    *ready   = 1;
    *blk_cnt = lun_info.capacity.block_nbr;
    *blk_sz  = lun_info.capacity.block_size ? lun_info.capacity.block_size : 512;
  }
  return 0;
}

void SPIA_Init(void)
{
  /* Nothing special: SPI1 SLAVE is already configured by CubeMX. */
}

/* Handle one command if present (non-blocking-ish). Call often. */
void SPIA_Service(void)
{
  uint8_t cmd;
  /* Try to get a command byte quickly; if none, return. */
  if (rx_bytes(&cmd, 1, 1) != 0) {
    return; // no clock activity / no command
  }

  if (cmd == 'Q') {
    uint8_t ready;
    uint32_t bc;
    uint16_t bs;
    get_media_info(&ready, &bc, &bs);

    uint8_t resp[1+1+1+4+2];
    resp[0] = 'Q';
    resp[1] = 'O';
    resp[2] = ready;
    resp[3] = be_u32(bc,0);
    resp[4] = be_u32(bc,1);
    resp[5] = be_u32(bc,2);
    resp[6] = be_u32(bc,3);
    resp[7] = be_u16(bs,0);
    resp[8] = be_u16(bs,1);
    (void)tx_bytes(resp, sizeof(resp), HAL_MAX_DELAY);
    return;
  }

  else if (cmd == 'R') {
    uint8_t hdr[6];
    if (rx_bytes(hdr, sizeof(hdr), HAL_MAX_DELAY)) return;

    uint32_t lba = ((uint32_t)hdr[0]<<24)|((uint32_t)hdr[1]<<16)|((uint32_t)hdr[2]<<8)|hdr[3];
    uint16_t cnt = ((uint16_t)hdr[4]<<8)|hdr[5];

    /* Sanity */
    uint8_t ready; uint32_t bc; uint16_t bs;
    get_media_info(&ready,&bc,&bs);
    if (!ready || cnt==0 || cnt>MAX_BLOCKS_PER_REQ || bs>MAX_BLOCK_SIZE) {
      uint8_t s[2] = {'O',1};
      (void)tx_bytes(s,2,HAL_MAX_DELAY);
      return;
    }

    /* Perform read via USB Host MSC */
    if (USBH_MSC_Read(&hUsbHostFS, 0, lba, xbuf, cnt) != USBH_OK) {
      uint8_t s[2] = {'O',1};
      (void)tx_bytes(s,2,HAL_MAX_DELAY);
      return;
    }

    /* OK status then payload */
    uint8_t s[2] = {'O',0};
    if (tx_bytes(s,2,HAL_MAX_DELAY)) return;
    (void)tx_bytes(xbuf, (uint16_t)(cnt*bs), HAL_MAX_DELAY);
    return;
  }

  else if (cmd == 'W') {
    uint8_t hdr[6];
    if (rx_bytes(hdr, sizeof(hdr), HAL_MAX_DELAY)) return;

    uint32_t lba = ((uint32_t)hdr[0]<<24)|((uint32_t)hdr[1]<<16)|((uint32_t)hdr[2]<<8)|hdr[3];
    uint16_t cnt = ((uint16_t)hdr[4]<<8)|hdr[5];

    uint8_t ready; uint32_t bc; uint16_t bs;
    get_media_info(&ready,&bc,&bs);
    if (!ready || cnt==0 || cnt>MAX_BLOCKS_PER_REQ || bs>MAX_BLOCK_SIZE) {
      uint8_t s[2] = {'O',1};
      (void)tx_bytes(s,2,HAL_MAX_DELAY);
      return;
    }

    /* Receive payload then write */
    if (rx_bytes(xbuf, (uint16_t)(cnt*bs), HAL_MAX_DELAY)) {
      uint8_t s[2] = {'O',1};
      (void)tx_bytes(s,2,HAL_MAX_DELAY);
      return;
    }

    if (USBH_MSC_Write(&hUsbHostFS, 0, lba, xbuf, cnt) != USBH_OK) {
      uint8_t s[2] = {'O',1};
      (void)tx_bytes(s,2,HAL_MAX_DELAY);
      return;
    }

    uint8_t s[2] = {'O',0};
    (void)tx_bytes(s,2,HAL_MAX_DELAY);
    return;
  }

  /* Unknown command: ignore gracefully */
}
